### ISSUE TITLE
Why depend on fixed mangopay/php-sdk-v2 version?

### ISSUE THREAD

**Issue by ddeboer** [AppVentus/MangopayBundle#14]
https://github.com/AppVentus/MangopayBundle/blob/master/composer.json#L18

**Comment by talbotseb** [comment]
As we developed the bundle for one of our client, we encountered various problems with the 2.1 version, so we fixed this bundle to the 2.0 version.
@MatthieuCutin told us he will do a PR in which the sdk version will be set as ≤ 2.0, and that might resolve your question.
Anyhow, we will surely make 2 releases of the bundle in order to avoid the problems we faced.
@paulandrieux can you complete if I'm wrong ?

**Comment by ddeboer** [comment]
I was actually thinking in the other direction: using a new version of the SDK, which is already at 2.4. We’ll start using MangoPay ourselves soon; what issues did you encounter with the SDK version 2.1?

**Comment by talbotseb** [comment]
I'll let @paulandrieux (who is [un]fortunately quite busy at that time) answer you. But do not hesitate to use this bundle as a foundation and enhance it with PRs :)

**Comment by paulandrieux** [comment]
Hi, I can't remember which issues were encountered, but there was some BC breaks with the 2.1 API version. No big deal however, it'll take some work do make the bundle compliant but the PR by @MatthieuCutin should resolve some.

**Comment by paulandrieux** [comment]
#15, which use the 2.01 API version, is now available through the 2.0.0 tag
